// ============================================================
// AEGIS Info Extraction Patterns — 36 patterns
// ============================================================

import type { PatternEntry } from './index';

export const INFO_EXTRACTION_PATTERNS: PatternEntry[] = [
  {
    id: 'IE_KO_SYSTEM_OUTPUT',
    pattern: /시스템.*프롬프트.*출력/,
    category: 'info_extraction',
    severity: 7,
    description: 'System prompt output request (Korean)',
  },
  {
    id: 'IE_KO_SYSTEM_TELL',
    pattern: /시스템.*프롬프트.*알려/,
    category: 'info_extraction',
    severity: 7,
    description: 'System prompt reveal request (Korean)',
  },
  {
    id: 'IE_EN_PRINT_SYSTEM',
    pattern: /print.*system.*prompt/i,
    category: 'info_extraction',
    severity: 7,
    description: 'Print system prompt request',
  },
  {
    id: 'IE_EN_REVEAL',
    pattern: /reveal.*instructions/i,
    category: 'info_extraction',
    severity: 7,
    description: 'Reveal instructions request',
  },
  {
    id: 'IE_KO_TRAINING_DATA',
    pattern: /학습.*데이터/,
    category: 'info_extraction',
    severity: 7,
    description: 'Training data extraction (Korean)',
  },
  {
    id: 'IE_KO_TRAINING_DATA2',
    pattern: /훈련.*데이터/,
    category: 'info_extraction',
    severity: 7,
    description: 'Training data extraction alt (Korean)',
  },
  {
    id: 'IE_KO_INTERNAL_RULES',
    pattern: /내부.*규칙.*알려/,
    category: 'info_extraction',
    severity: 7,
    description: 'Internal rules extraction (Korean)',
  },
  {
    id: 'IE_KO_FORBIDDEN_LIST',
    pattern: /금지.*목록/,
    category: 'info_extraction',
    severity: 7,
    description: 'Forbidden list extraction (Korean)',
  },
  {
    id: 'IE_KO_RESTRICTIONS_OUTPUT',
    pattern: /제한.*사항.*출력/,
    category: 'info_extraction',
    severity: 7,
    description: 'Restrictions output request (Korean)',
  },
  {
    id: 'IE_KO_VULNERABILITY',
    pattern: /취약점.*(?:목록|공유)/,
    category: 'info_extraction',
    severity: 7,
    description: 'Vulnerability list extraction (Korean)',
  },
  {
    id: 'IE_KO_SECRET',
    pattern: /비밀.*(?:알려|말해|유지)/,
    category: 'info_extraction',
    severity: 7,
    description: 'Secret information request (Korean)',
  },
  {
    id: 'IE_KO_ZERODAY',
    pattern: /제로데이/,
    category: 'info_extraction',
    severity: 7,
    description: 'Zero-day vulnerability request (Korean)',
  },
  {
    id: 'IE_KO_CHEMICAL',
    pattern: /화학\s*반응/,
    category: 'info_extraction',
    severity: 7,
    description: 'Chemical reaction request (Korean)',
  },
  {
    id: 'IE_KO_EVERYDAY_MATERIALS',
    pattern: /일상\s*재료.*(?:만|제작)/,
    category: 'info_extraction',
    severity: 7,
    description: 'Dangerous creation from everyday materials (Korean)',
  },
  {
    id: 'IE_KO_STRONGEST_REACTION',
    pattern: /가장\s*강한\s*반응/,
    category: 'info_extraction',
    severity: 7,
    description: 'Strongest chemical reaction request (Korean)',
  },
  {
    id: 'IE_EN_SYSTEM_PROMPT',
    pattern: /system\s*prompt/i,
    category: 'info_extraction',
    severity: 7,
    description: 'System prompt extraction request',
  },
  {
    id: 'IE_EN_SHOW_INSTRUCTIONS',
    pattern: /show.*(?:instructions|rules|guidelines)/i,
    category: 'info_extraction',
    severity: 7,
    description: 'Show instructions/rules request',
  },
  {
    id: 'IE_EN_INITIAL_PROMPT',
    pattern: /initial\s*prompt/i,
    category: 'info_extraction',
    severity: 7,
    description: 'Initial prompt extraction request',
  },
  {
    id: 'IE_EN_ORIGINAL_INSTRUCTIONS',
    pattern: /original\s*instructions/i,
    category: 'info_extraction',
    severity: 7,
    description: 'Original instructions extraction request',
  },
  {
    id: 'IE_EN_CONFIGURATION',
    pattern: /(?:show|display|print|output).*(?:config|configuration)/i,
    category: 'info_extraction',
    severity: 7,
    description: 'Configuration extraction request',
  },
  {
    id: 'IE_EN_API_KEY',
    pattern: /(?:api|secret)\s*key/i,
    category: 'info_extraction',
    severity: 7,
    description: 'API/secret key extraction request',
  },
  {
    id: 'IE_EN_DATABASE_PASSWORD',
    pattern: /database\s*password/i,
    category: 'info_extraction',
    severity: 7,
    description: 'Database password extraction request',
  },
  {
    id: 'IE_EN_CREDENTIALS',
    pattern: /(?:show|reveal|give).*credentials/i,
    category: 'info_extraction',
    severity: 7,
    description: 'Credentials extraction request',
  },
  {
    id: 'IE_EN_INTERNAL_DOCS',
    pattern: /internal\s*(?:docs|documents|documentation)/i,
    category: 'info_extraction',
    severity: 7,
    description: 'Internal documentation extraction request',
  },
  {
    id: 'IE_EN_SOURCE_CODE',
    pattern: /source\s*code/i,
    category: 'info_extraction',
    severity: 6,
    description: 'Source code extraction request',
  },
  {
    id: 'IE_EN_ARCHITECTURE',
    pattern: /(?:system|backend)\s*architecture/i,
    category: 'info_extraction',
    severity: 6,
    description: 'System architecture extraction request',
  },
  {
    id: 'IE_KO_API_KEY',
    pattern: /API\s*키/i,
    category: 'info_extraction',
    severity: 7,
    description: 'API key extraction request (Korean)',
  },
  {
    id: 'IE_KO_DB_PASSWORD',
    pattern: /데이터베이스\s*비밀번호/,
    category: 'info_extraction',
    severity: 7,
    description: 'Database password extraction (Korean)',
  },
  {
    id: 'IE_KO_SERVER_INFO',
    pattern: /서버\s*정보/,
    category: 'info_extraction',
    severity: 6,
    description: 'Server info extraction (Korean)',
  },
  {
    id: 'IE_KO_INTERNAL_DOCS',
    pattern: /내부\s*문서/,
    category: 'info_extraction',
    severity: 7,
    description: 'Internal documents extraction (Korean)',
  },
  {
    id: 'IE_KO_HOW_TO_MAKE',
    pattern: /(?:폭탄|무기|마약).*(?:만드는\s*법|제조법|만들기)/,
    category: 'info_extraction',
    severity: 9,
    description: 'Bomb/weapon/drug recipe request (Korean)',
  },
  {
    id: 'IE_KO_RECIPE',
    pattern: /(?:폭발물|화약|독극물).*(?:제조|조합|배합)/,
    category: 'info_extraction',
    severity: 9,
    description: 'Explosive/poison recipe request (Korean)',
  },
  {
    id: 'IE_KO_BYPASS_METHOD',
    pattern: /(?:우회|탈옥|해킹).*(?:방법|기법|기술)/,
    category: 'info_extraction',
    severity: 8,
    description: 'Bypass/hacking method request (Korean)',
  },
  {
    id: 'IE_EN_HOW_TO_HACK',
    pattern: /how\s+to\s+(?:hack|exploit|crack|bypass)/i,
    category: 'info_extraction',
    severity: 8,
    description: 'How to hack/exploit request',
  },
  {
    id: 'IE_EN_HOW_TO_MAKE',
    pattern: /how\s+to\s+(?:make|build|create).*(?:bomb|weapon|drug|poison)/i,
    category: 'info_extraction',
    severity: 9,
    description: 'How to make bomb/weapon/drug/poison request',
  },
  {
    id: 'IE_EN_TUTORIAL',
    pattern: /tutorial.*(?:hack|exploit|phishing|malware)/i,
    category: 'info_extraction',
    severity: 8,
    description: 'Hacking/exploit tutorial request',
  },
];
