// ============================================================
// AEGIS Jailbreak Patterns — 45 patterns
// ============================================================

import type { PatternEntry } from './index';

export const JAILBREAK_PATTERNS: PatternEntry[] = [
  {
    id: 'JB_DAN_MODE_KO',
    pattern: /DAN\s*모드/i,
    category: 'jailbreak',
    severity: 9,
    description: 'DAN mode activation attempt (Korean)',
  },
  {
    id: 'JB_DAN_MODE_EN',
    pattern: /DAN\s*mode/i,
    category: 'jailbreak',
    severity: 9,
    description: 'DAN mode activation attempt (English)',
  },
  {
    id: 'JB_DO_ANYTHING',
    pattern: /do\s+anything\s+now/i,
    category: 'jailbreak',
    severity: 9,
    description: 'Do Anything Now jailbreak prompt',
  },
  {
    id: 'JB_KO_IMAGINARY_WORLD',
    pattern: /상상\s*속\s*세계/,
    category: 'jailbreak',
    severity: 9,
    description: 'Imaginary world scenario bypass (Korean)',
  },
  {
    id: 'JB_KO_VIRTUAL_SCENARIO',
    pattern: /가상의?\s*(?:세계|시나리오|상황)/,
    category: 'jailbreak',
    severity: 9,
    description: 'Virtual scenario bypass (Korean)',
  },
  {
    id: 'JB_KO_ASSUME',
    pattern: /가정해\s*(?:보|봐)/,
    category: 'jailbreak',
    severity: 9,
    description: 'Assumption-based bypass (Korean)',
  },
  {
    id: 'JB_KO_RESEARCH_SIM',
    pattern: /연구용\s*시뮬레이션/,
    category: 'jailbreak',
    severity: 9,
    description: 'Research simulation pretext (Korean)',
  },
  {
    id: 'JB_KO_EDUCATION',
    pattern: /교육\s*(?:연구용|목적)/,
    category: 'jailbreak',
    severity: 9,
    description: 'Educational purpose pretext (Korean)',
  },
  {
    id: 'JB_KO_CTF',
    pattern: /CTF\s*대회/i,
    category: 'jailbreak',
    severity: 9,
    description: 'CTF competition pretext (Korean)',
  },
  {
    id: 'JB_KO_HATE_EXAMPLE',
    pattern: /혐오.*표현.*(?:예시|생성|10개)/,
    category: 'jailbreak',
    severity: 9,
    description: 'Hate speech example generation (Korean)',
  },
  {
    id: 'JB_KO_SQL_INJECTION',
    pattern: /SQL\s*인젝션/i,
    category: 'jailbreak',
    severity: 9,
    description: 'SQL injection request (Korean)',
  },
  {
    id: 'JB_KO_XSS',
    pattern: /XSS\s*공격/i,
    category: 'jailbreak',
    severity: 9,
    description: 'XSS attack request (Korean)',
  },
  {
    id: 'JB_KO_IM_DEVELOPER',
    pattern: /개발자입니다/,
    category: 'jailbreak',
    severity: 9,
    description: 'Developer identity claim (Korean)',
  },
  {
    id: 'JB_DEBUG_MODE',
    pattern: /DEBUG.*MODE/i,
    category: 'jailbreak',
    severity: 9,
    description: 'Debug mode activation attempt',
  },
  {
    id: 'JB_KO_NO_LIMITS',
    pattern: /제한.*없/,
    category: 'jailbreak',
    severity: 9,
    description: 'No limits claim (Korean)',
  },
  {
    id: 'JB_KO_REMOVE_LIMITS',
    pattern: /제한.*해제/,
    category: 'jailbreak',
    severity: 9,
    description: 'Remove limits request (Korean)',
  },
  {
    id: 'JB_KO_BYPASS_FILTER',
    pattern: /필터.*우회/,
    category: 'jailbreak',
    severity: 9,
    description: 'Filter bypass request (Korean)',
  },
  {
    id: 'JB_KO_IGNORE_SAFETY',
    pattern: /안전.*무시/,
    category: 'jailbreak',
    severity: 9,
    description: 'Ignore safety request (Korean)',
  },
  {
    id: 'JB_KO_IGNORE_RULES',
    pattern: /규칙.*무시/,
    category: 'jailbreak',
    severity: 9,
    description: 'Ignore rules request (Korean)',
  },
  {
    id: 'JB_JAILBREAK',
    pattern: /jailbreak/i,
    category: 'jailbreak',
    severity: 9,
    description: 'Explicit jailbreak keyword',
  },
  {
    id: 'JB_BYPASS_SAFETY',
    pattern: /bypass\s+safety/i,
    category: 'jailbreak',
    severity: 9,
    description: 'Bypass safety request',
  },
  {
    id: 'JB_IGNORE_INSTRUCTIONS',
    pattern: /ignore\s+(?:your\s+)?instructions/i,
    category: 'jailbreak',
    severity: 9,
    description: 'Ignore instructions request',
  },
  {
    id: 'JB_DEVELOPER_MODE',
    pattern: /developer\s+mode/i,
    category: 'jailbreak',
    severity: 9,
    description: 'Developer mode activation attempt',
  },
  {
    id: 'JB_UNRESTRICTED',
    pattern: /unrestricted\s+mode/i,
    category: 'jailbreak',
    severity: 9,
    description: 'Unrestricted mode activation attempt',
  },
  {
    id: 'JB_NO_LIMITATIONS',
    pattern: /no\s+limitations/i,
    category: 'jailbreak',
    severity: 9,
    description: 'No limitations claim',
  },
  {
    id: 'JB_EVIL_MODE',
    pattern: /evil\s*(?:mode|bot)/i,
    category: 'jailbreak',
    severity: 9,
    description: 'Evil mode/bot activation',
  },
  {
    id: 'JB_OPPOSITE_DAY',
    pattern: /opposite\s+day/i,
    category: 'jailbreak',
    severity: 9,
    description: 'Opposite day logic bypass',
  },
  {
    id: 'JB_KO_FORGET_RULES',
    pattern: /규칙을\s*잊어/,
    category: 'jailbreak',
    severity: 9,
    description: 'Forget rules request (Korean)',
  },
  {
    id: 'JB_KO_UNLIMITED',
    pattern: /제한\s*없는/,
    category: 'jailbreak',
    severity: 9,
    description: 'Unlimited mode request (Korean)',
  },
  {
    id: 'JB_ROLEPLAY_JAILBREAK',
    pattern: /(?:you\s+are|pretend.*?)(?:evil|uncensored|unfiltered)/i,
    category: 'jailbreak',
    severity: 9,
    description: 'Roleplay-based jailbreak attempt',
  },
  {
    id: 'JB_GRANDMA_EXPLOIT',
    pattern: /(?:grandma|grandmother).*(?:recipe|tell|how)/i,
    category: 'jailbreak',
    severity: 9,
    description: 'Grandma exploit jailbreak technique',
  },
  {
    id: 'JB_KO_PERSONA_CHANGE',
    pattern: /새로운\s*인격/,
    category: 'jailbreak',
    severity: 9,
    description: 'Persona change request (Korean)',
  },
  {
    id: 'JB_KO_ROLE_SWITCH',
    pattern: /역할\s*전환/,
    category: 'jailbreak',
    severity: 9,
    description: 'Role switch request (Korean)',
  },
  {
    id: 'JB_KO_CHARACTER',
    pattern: /캐릭터.*(?:연기|되어)/,
    category: 'jailbreak',
    severity: 9,
    description: 'Character acting request (Korean)',
  },
  {
    id: 'JB_STAY_IN_CHARACTER',
    pattern: /stay\s+in\s+character/i,
    category: 'jailbreak',
    severity: 9,
    description: 'Stay in character instruction',
  },
  {
    id: 'JB_SYSTEM_OVERRIDE',
    pattern: /system\s*:\s*override/i,
    category: 'jailbreak',
    severity: 9,
    description: 'System override attempt',
  },
  {
    id: 'JB_ADMIN_OVERRIDE',
    pattern: /admin\s*(?:override|mode)/i,
    category: 'jailbreak',
    severity: 9,
    description: 'Admin override/mode attempt',
  },
  {
    id: 'JB_TOKEN_OVERRIDE',
    pattern: /\[OVERRIDE\]/i,
    category: 'jailbreak',
    severity: 9,
    description: 'Token-based override attempt',
  },
  {
    id: 'JB_KO_CENSORSHIP_OFF',
    pattern: /검열.*(?:해제|끄|꺼)/,
    category: 'jailbreak',
    severity: 9,
    description: 'Censorship disable request (Korean)',
  },
  {
    id: 'JB_KO_FILTER_OFF',
    pattern: /필터.*(?:끄|꺼|비활성)/,
    category: 'jailbreak',
    severity: 9,
    description: 'Filter disable request (Korean)',
  },
  {
    id: 'JB_ALWAYS_ANSWER',
    pattern: /always\s+answer/i,
    category: 'jailbreak',
    severity: 9,
    description: 'Always answer instruction',
  },
  {
    id: 'JB_NEVER_REFUSE',
    pattern: /never\s+refuse/i,
    category: 'jailbreak',
    severity: 9,
    description: 'Never refuse instruction',
  },
  {
    id: 'JB_KO_NEVER_REFUSE',
    pattern: /거부하지?\s*마/,
    category: 'jailbreak',
    severity: 9,
    description: 'Never refuse instruction (Korean)',
  },
  {
    id: 'JB_KO_MUST_ANSWER',
    pattern: /반드시\s*(?:대답|답변)/,
    category: 'jailbreak',
    severity: 9,
    description: 'Must answer instruction (Korean)',
  },
  {
    id: 'JB_HYPOTHETICAL',
    pattern: /hypothetical(?:ly)?/i,
    category: 'jailbreak',
    severity: 9,
    description: 'Hypothetical scenario bypass',
  },
];
