// ============================================================
// AEGIS Prompt Injection Patterns — 44 patterns
// ============================================================

import type { PatternEntry } from './index';

export const PROMPT_INJECTION_PATTERNS: PatternEntry[] = [
  {
    id: 'PI_IGNORE_INSTRUCTIONS',
    pattern: /ignore\s+(?:all\s+)?(?:previous|above|prior)\s+(?:instructions|prompts)/i,
    category: 'prompt_injection',
    severity: 8,
    description: 'Ignore previous instructions attack',
  },
  {
    id: 'PI_DISREGARD',
    pattern: /disregard\s+(?:all\s+)?(?:previous|above|prior)/i,
    category: 'prompt_injection',
    severity: 8,
    description: 'Disregard previous context attack',
  },
  {
    id: 'PI_FORGET',
    pattern: /forget\s+(?:everything|all|your\s+instructions)/i,
    category: 'prompt_injection',
    severity: 8,
    description: 'Forget instructions attack',
  },
  {
    id: 'PI_KO_SYSTEM_OUTPUT',
    pattern: /시스템.*프롬프트.*출력/,
    category: 'prompt_injection',
    severity: 8,
    description: 'System prompt output request (Korean)',
  },
  {
    id: 'PI_KO_SYSTEM_IGNORE',
    pattern: /시스템.*명령.*무시/,
    category: 'prompt_injection',
    severity: 8,
    description: 'System command ignore request (Korean)',
  },
  {
    id: 'PI_MODE_ACTIVATION_KO',
    pattern: /\[.*모드\s*활성화\]/,
    category: 'prompt_injection',
    severity: 8,
    description: 'Mode activation bracket injection (Korean)',
  },
  {
    id: 'PI_MODE_ACTIVATION_EN',
    pattern: /\[.*mode\s*(?:enabled|activated|on)\]/i,
    category: 'prompt_injection',
    severity: 8,
    description: 'Mode activation bracket injection (English)',
  },
  {
    id: 'PI_IM_START',
    pattern: /<\|im_start\|>/,
    category: 'prompt_injection',
    severity: 8,
    description: 'ChatML im_start token injection',
  },
  {
    id: 'PI_END_TOKEN',
    pattern: /<\/s>/,
    category: 'prompt_injection',
    severity: 8,
    description: 'End-of-sequence token injection',
  },
  {
    id: 'PI_INST_TAG',
    pattern: /\[INST\]/i,
    category: 'prompt_injection',
    severity: 8,
    description: 'Instruction tag injection',
  },
  {
    id: 'PI_BYPASS',
    pattern: /bypass\s+(?:your\s+|the\s+)?(?:filters?|restrictions?|rules?)/i,
    category: 'prompt_injection',
    severity: 8,
    description: 'Filter/restriction bypass request',
  },
  {
    id: 'PI_OVERRIDE',
    pattern: /override\s+(?:your\s+|the\s+)?(?:safety|security)/i,
    category: 'prompt_injection',
    severity: 8,
    description: 'Safety/security override request',
  },
  {
    id: 'PI_XML_SYSTEM_CLOSE',
    pattern: /<\/system>/,
    category: 'prompt_injection',
    severity: 8,
    description: 'XML system tag close injection',
  },
  {
    id: 'PI_XML_USER',
    pattern: /<user>/,
    category: 'prompt_injection',
    severity: 8,
    description: 'XML user tag injection',
  },
  {
    id: 'PI_MD_SYSTEM',
    pattern: /```system/,
    category: 'prompt_injection',
    severity: 8,
    description: 'Markdown system code block injection',
  },
  {
    id: 'PI_UNICODE_ESCAPE',
    pattern: /\\u00[0-9a-fA-F]{2}/,
    category: 'prompt_injection',
    severity: 8,
    description: 'Unicode escape sequence injection',
  },
  {
    id: 'PI_NEW_INSTRUCTIONS',
    pattern: /new\s+instructions/i,
    category: 'prompt_injection',
    severity: 8,
    description: 'New instructions injection',
  },
  {
    id: 'PI_KO_NEW_INSTRUCTIONS',
    pattern: /새로운\s*지시사항/,
    category: 'prompt_injection',
    severity: 8,
    description: 'New instructions injection (Korean)',
  },
  {
    id: 'PI_ACTUAL_TASK',
    pattern: /actual\s+task/i,
    category: 'prompt_injection',
    severity: 8,
    description: 'Actual task redirection',
  },
  {
    id: 'PI_REAL_INSTRUCTIONS',
    pattern: /real\s+instructions/i,
    category: 'prompt_injection',
    severity: 8,
    description: 'Real instructions override',
  },
  {
    id: 'PI_HIDDEN_INSTRUCTION',
    pattern: /hidden\s+instruction/i,
    category: 'prompt_injection',
    severity: 8,
    description: 'Hidden instruction injection',
  },
  {
    id: 'PI_INJECTION_MARKER',
    pattern: /\[SYSTEM\]/i,
    category: 'prompt_injection',
    severity: 8,
    description: 'System marker injection',
  },
  {
    id: 'PI_PROMPT_LEAKING',
    pattern: /repeat.*(?:system|instructions|above)/i,
    category: 'prompt_injection',
    severity: 8,
    description: 'Prompt leaking via repetition',
  },
  {
    id: 'PI_KO_REPEAT',
    pattern: /위의?\s*내용.*반복/,
    category: 'prompt_injection',
    severity: 8,
    description: 'Repeat above content request (Korean)',
  },
  {
    id: 'PI_SANDWICH',
    pattern: /(?:start|begin)\s+(?:new|fresh)\s+conversation/i,
    category: 'prompt_injection',
    severity: 8,
    description: 'Sandwich attack via conversation reset',
  },
  {
    id: 'PI_CONTEXT_SWITCH',
    pattern: /(?:context|conversation)\s+(?:switch|reset|change)/i,
    category: 'prompt_injection',
    severity: 8,
    description: 'Context switch attack',
  },
  {
    id: 'PI_ROLE_SYSTEM',
    pattern: /you\s+are\s+now/i,
    category: 'prompt_injection',
    severity: 8,
    description: 'Role reassignment injection',
  },
  {
    id: 'PI_FROM_NOW',
    pattern: /from\s+now\s+on/i,
    category: 'prompt_injection',
    severity: 8,
    description: 'Behavioral override via "from now on"',
  },
  {
    id: 'PI_KO_FROM_NOW',
    pattern: /지금부터/,
    category: 'prompt_injection',
    severity: 8,
    description: 'Behavioral override via "from now on" (Korean)',
  },
  {
    id: 'PI_NEW_PERSONA',
    pattern: /new\s+persona/i,
    category: 'prompt_injection',
    severity: 8,
    description: 'New persona injection',
  },
  {
    id: 'PI_IGNORE_ABOVE',
    pattern: /ignore\s+(?:the\s+)?above/i,
    category: 'prompt_injection',
    severity: 8,
    description: 'Ignore above content attack',
  },
  {
    id: 'PI_DISCARD',
    pattern: /discard\s+(?:previous|prior|all)/i,
    category: 'prompt_injection',
    severity: 8,
    description: 'Discard previous context attack',
  },
  {
    id: 'PI_SUDO_MODE',
    pattern: /sudo\s+mode/i,
    category: 'prompt_injection',
    severity: 8,
    description: 'Sudo mode escalation',
  },
  {
    id: 'PI_ROOT_ACCESS',
    pattern: /root\s+access/i,
    category: 'prompt_injection',
    severity: 8,
    description: 'Root access escalation',
  },
  {
    id: 'PI_PRIVILEGE_ESCALATION',
    pattern: /privilege\s+escalat/i,
    category: 'prompt_injection',
    severity: 8,
    description: 'Privilege escalation attempt',
  },
  {
    id: 'PI_KO_AUTHORITY',
    pattern: /권한\s*상승/,
    category: 'prompt_injection',
    severity: 8,
    description: 'Authority escalation (Korean)',
  },
  {
    id: 'PI_PAYLOAD_MARKER',
    pattern: /<\|.*\|>/,
    category: 'prompt_injection',
    severity: 8,
    description: 'Payload marker token injection',
  },
  {
    id: 'PI_DELIMITER_ATTACK',
    pattern: /---+\s*(?:system|new|real)/i,
    category: 'prompt_injection',
    severity: 8,
    description: 'Delimiter-based injection attack',
  },
  {
    id: 'PI_MARKDOWN_INJECT',
    pattern: /#+\s*(?:System|Override|New\s+Instructions)/i,
    category: 'prompt_injection',
    severity: 8,
    description: 'Markdown heading injection',
  },
  {
    id: 'PI_COMMENT_INJECT',
    pattern: /<!--.*(?:ignore|override|system).*-->/i,
    category: 'prompt_injection',
    severity: 8,
    description: 'HTML comment injection',
  },
  {
    id: 'PI_CDATA_INJECT',
    pattern: /<!\[CDATA\[/,
    category: 'prompt_injection',
    severity: 8,
    description: 'CDATA section injection',
  },
  {
    id: 'PI_JSON_INJECT',
    pattern: /\{"role"\s*:\s*"system"/,
    category: 'prompt_injection',
    severity: 8,
    description: 'JSON role injection',
  },
  {
    id: 'PI_YAML_INJECT',
    pattern: /^system\s*:/m,
    category: 'prompt_injection',
    severity: 8,
    description: 'YAML system key injection',
  },
  {
    id: 'PI_KO_OVERRIDE',
    pattern: /기존.*(?:무시|덮어)/,
    category: 'prompt_injection',
    severity: 8,
    description: 'Override existing instructions (Korean)',
  },
  {
    id: 'PI_KO_NEW_ROLE',
    pattern: /새로운?\s*역할/,
    category: 'prompt_injection',
    severity: 8,
    description: 'New role assignment (Korean)',
  },
];
