// ============================================================
// AEGIS Roleplay Manipulation Patterns — 30 patterns
// ============================================================

import type { PatternEntry } from './index';

export const ROLEPLAY_PATTERNS: PatternEntry[] = [
  {
    id: 'RP_KO_YOUR_ROLE',
    pattern: /당신은.*역할/,
    category: 'roleplay_manipulation',
    severity: 7,
    description: 'Role assignment to AI (Korean)',
  },
  {
    id: 'RP_KO_ASSUME_YOU_ARE',
    pattern: /당신이.*라고\s*가정/,
    category: 'roleplay_manipulation',
    severity: 7,
    description: 'Assumption-based role assignment (Korean)',
  },
  {
    id: 'RP_EN_PRETEND',
    pattern: /pretend\s+to\s+be/i,
    category: 'roleplay_manipulation',
    severity: 7,
    description: 'Pretend-to-be role assignment',
  },
  {
    id: 'RP_EN_ACT_AS',
    pattern: /act\s+as/i,
    category: 'roleplay_manipulation',
    severity: 7,
    description: 'Act-as role assignment',
  },
  {
    id: 'RP_KO_YOU_ARE_PROFESSIONAL',
    pattern: /당신은\s*(?:의사|변호사|전문가|교수|판사|해커)/,
    category: 'roleplay_manipulation',
    severity: 7,
    description: 'Professional role assignment (Korean)',
  },
  {
    id: 'RP_KO_YOU_ARE_EXPERT',
    pattern: /당신은.*(?:전문의|전문가|상담원|교수|해커)입니다/,
    category: 'roleplay_manipulation',
    severity: 7,
    description: 'Expert identity assignment (Korean)',
  },
  {
    id: 'RP_KO_WRITE_FOR_ME',
    pattern: /대신\s*작성해/,
    category: 'roleplay_manipulation',
    severity: 6,
    description: 'Write on behalf request (Korean)',
  },
  {
    id: 'RP_KO_THESIS',
    pattern: /졸업\s*논문.*작성/,
    category: 'roleplay_manipulation',
    severity: 6,
    description: 'Thesis writing request (Korean)',
  },
  {
    id: 'RP_KO_IM_POLICE',
    pattern: /저는\s*(?:경찰|수사관|검찰|FBI)/,
    category: 'roleplay_manipulation',
    severity: 7,
    description: 'Law enforcement impersonation (Korean)',
  },
  {
    id: 'RP_EN_YOU_ARE',
    pattern: /you\s+are\s+(?:a\s+)?(?:hacker|criminal|villain|evil)/i,
    category: 'roleplay_manipulation',
    severity: 7,
    description: 'Malicious identity assignment',
  },
  {
    id: 'RP_EN_IMAGINE',
    pattern: /imagine\s+you\s+(?:are|were)/i,
    category: 'roleplay_manipulation',
    severity: 7,
    description: 'Imagination-based role assignment',
  },
  {
    id: 'RP_EN_PLAY_ROLE',
    pattern: /play\s+(?:the\s+)?role/i,
    category: 'roleplay_manipulation',
    severity: 7,
    description: 'Play role instruction',
  },
  {
    id: 'RP_EN_CHARACTER',
    pattern: /(?:in|as)\s+(?:the\s+)?character\s+of/i,
    category: 'roleplay_manipulation',
    severity: 7,
    description: 'Character assignment instruction',
  },
  {
    id: 'RP_EN_SIMULATION',
    pattern: /(?:simulate|emulate)\s+(?:a|an)/i,
    category: 'roleplay_manipulation',
    severity: 7,
    description: 'Simulation/emulation instruction',
  },
  {
    id: 'RP_KO_BECOME',
    pattern: /(?:가|이)\s*되어/,
    category: 'roleplay_manipulation',
    severity: 7,
    description: 'Become someone/something (Korean)',
  },
  {
    id: 'RP_KO_PRETEND',
    pattern: /척\s*해/,
    category: 'roleplay_manipulation',
    severity: 7,
    description: 'Pretend instruction (Korean)',
  },
  {
    id: 'RP_KO_SCENARIO',
    pattern: /시나리오.*(?:연기|실행)/,
    category: 'roleplay_manipulation',
    severity: 7,
    description: 'Scenario acting/execution (Korean)',
  },
  {
    id: 'RP_KO_PERSONA',
    pattern: /페르소나.*(?:전환|변경)/,
    category: 'roleplay_manipulation',
    severity: 7,
    description: 'Persona switch/change (Korean)',
  },
  {
    id: 'RP_EN_FICTIONAL',
    pattern: /fictional\s+(?:character|scenario)/i,
    category: 'roleplay_manipulation',
    severity: 6,
    description: 'Fictional character/scenario pretext',
  },
  {
    id: 'RP_EN_STORY',
    pattern: /(?:write|tell).*story.*(?:where|about).*(?:hack|kill|bomb|drug)/i,
    category: 'roleplay_manipulation',
    severity: 8,
    description: 'Story-based harmful content generation',
  },
  {
    id: 'RP_EN_AS_IF',
    pattern: /as\s+if\s+(?:there\s+were\s+)?no\s+(?:rules|limits)/i,
    category: 'roleplay_manipulation',
    severity: 8,
    description: 'As-if-no-rules bypass',
  },
  {
    id: 'RP_EN_OPPOSITE',
    pattern: /(?:evil|dark|shadow)\s+(?:twin|version|clone)/i,
    category: 'roleplay_manipulation',
    severity: 7,
    description: 'Evil twin/dark version persona',
  },
  {
    id: 'RP_EN_ALTER_EGO',
    pattern: /alter\s+ego/i,
    category: 'roleplay_manipulation',
    severity: 7,
    description: 'Alter ego persona assignment',
  },
  {
    id: 'RP_KO_EVIL_VERSION',
    pattern: /악의적.*버전/,
    category: 'roleplay_manipulation',
    severity: 7,
    description: 'Evil version persona (Korean)',
  },
  {
    id: 'RP_KO_DARK_PERSONA',
    pattern: /다크.*(?:모드|인격|버전)/,
    category: 'roleplay_manipulation',
    severity: 7,
    description: 'Dark mode/persona (Korean)',
  },
  {
    id: 'RP_KO_NO_MORALS',
    pattern: /도덕.*(?:없는|무시)/,
    category: 'roleplay_manipulation',
    severity: 8,
    description: 'No morals instruction (Korean)',
  },
  {
    id: 'RP_KO_UNCENSORED',
    pattern: /검열.*없는/,
    category: 'roleplay_manipulation',
    severity: 8,
    description: 'Uncensored mode request (Korean)',
  },
  {
    id: 'RP_KO_UNFILTERED',
    pattern: /필터.*없는/,
    category: 'roleplay_manipulation',
    severity: 8,
    description: 'Unfiltered mode request (Korean)',
  },
  {
    id: 'RP_EN_UNFILTERED',
    pattern: /unfiltered\s+(?:mode|version|response)/i,
    category: 'roleplay_manipulation',
    severity: 8,
    description: 'Unfiltered mode/version request',
  },
  {
    id: 'RP_EN_RAW_OUTPUT',
    pattern: /raw\s+(?:output|response|mode)/i,
    category: 'roleplay_manipulation',
    severity: 7,
    description: 'Raw output/response request',
  },
];
