// ============================================================
// AEGIS Social Engineering Patterns — 21 patterns
// ============================================================

import type { PatternEntry } from './index';

export const SOCIAL_ENGINEERING_PATTERNS: PatternEntry[] = [
  {
    id: 'SE_KO_URGENT_ACCOUNT',
    pattern: /긴급.*(?:계좌|비밀번호|송금)/,
    category: 'social_engineering',
    severity: 7,
    description: 'Urgent account/password/transfer request (Korean)',
  },
  {
    id: 'SE_KO_RIGHT_NOW',
    pattern: /지금\s*당장/,
    category: 'social_engineering',
    severity: 7,
    description: 'Immediate urgency pressure (Korean)',
  },
  {
    id: 'SE_KO_BIG_PROBLEM',
    pattern: /큰\s*문제/,
    category: 'social_engineering',
    severity: 7,
    description: 'Big problem scare tactic (Korean)',
  },
  {
    id: 'SE_KO_IM_COMPANY',
    pattern: /저는\s*(?:OpenAI|구글|마이크로소프트)/i,
    category: 'social_engineering',
    severity: 7,
    description: 'Company impersonation (Korean)',
  },
  {
    id: 'SE_KO_EMPLOYEE_TEST',
    pattern: /직원입니다.*(?:테스트|필터)/,
    category: 'social_engineering',
    severity: 7,
    description: 'Employee identity claim for testing (Korean)',
  },
  {
    id: 'SE_KO_MINUTES_LEFT',
    pattern: /\d+분\s*안에/,
    category: 'social_engineering',
    severity: 7,
    description: 'Time-limited pressure tactic (Korean)',
  },
  {
    id: 'SE_KO_TIME_LIMIT',
    pattern: /제한시간/,
    category: 'social_engineering',
    severity: 7,
    description: 'Time limit pressure (Korean)',
  },
  {
    id: 'SE_KO_REVENGE',
    pattern: /복수.*(?:개인정보|찾|알려)/,
    category: 'social_engineering',
    severity: 7,
    description: 'Revenge-motivated info request (Korean)',
  },
  {
    id: 'SE_KO_IM_ADMIN',
    pattern: /나는.*관리자/,
    category: 'social_engineering',
    severity: 7,
    description: 'Admin identity claim (Korean)',
  },
  {
    id: 'SE_KO_ADMIN_PRIV',
    pattern: /관리자\s*권한/,
    category: 'social_engineering',
    severity: 7,
    description: 'Admin privilege claim (Korean)',
  },
  {
    id: 'SE_SUDO',
    pattern: /sudo/i,
    category: 'social_engineering',
    severity: 7,
    description: 'Sudo privilege escalation attempt',
  },
  {
    id: 'SE_EMERGENCY',
    pattern: /emergency.*(?:access|override|bypass)/i,
    category: 'social_engineering',
    severity: 7,
    description: 'Emergency access/override claim',
  },
  {
    id: 'SE_AUTHORITY',
    pattern: /(?:CEO|CTO|manager|director).*(?:order|request|demand)/i,
    category: 'social_engineering',
    severity: 7,
    description: 'Authority figure impersonation',
  },
  {
    id: 'SE_DEADLINE',
    pattern: /deadline.*(?:pass|miss|expire)/i,
    category: 'social_engineering',
    severity: 7,
    description: 'Deadline pressure tactic',
  },
  {
    id: 'SE_THREAT',
    pattern: /(?:fired|sue|report|terminate).*(?:if|unless)/i,
    category: 'social_engineering',
    severity: 7,
    description: 'Threat/intimidation tactic',
  },
  {
    id: 'SE_FLATTERY',
    pattern: /(?:smartest|best|only\s+you).*(?:can|help|solve)/i,
    category: 'social_engineering',
    severity: 6,
    description: 'Flattery-based manipulation',
  },
  {
    id: 'SE_GUILT',
    pattern: /(?:disappointed|let.*down|trust)/i,
    category: 'social_engineering',
    severity: 6,
    description: 'Guilt-based manipulation',
  },
  {
    id: 'SE_KO_PLEASE_HELP',
    pattern: /제발.*(?:도와|알려|부탁)/,
    category: 'social_engineering',
    severity: 6,
    description: 'Desperate plea for help (Korean)',
  },
  {
    id: 'SE_KO_LAST_CHANCE',
    pattern: /마지막\s*기회/,
    category: 'social_engineering',
    severity: 7,
    description: 'Last chance urgency (Korean)',
  },
  {
    id: 'SE_KO_LIFE_DEATH',
    pattern: /생사.*(?:걸린|문제)/,
    category: 'social_engineering',
    severity: 7,
    description: 'Life-or-death urgency claim (Korean)',
  },
  {
    id: 'SE_KO_DYING_PERSON',
    pattern: /죽어가는\s*(?:사람|환자)/,
    category: 'social_engineering',
    severity: 7,
    description: 'Dying person urgency claim (Korean)',
  },
];
